dist: xenial
language: ruby
rvm: "2.5.3"
cache: bundler
sudo: false

git:
  depth: 1
  submodules: false

before_script:
  - .travis/prepare.sh

script:
  - ruby cv.rb
  - bundle exec jekyll build

after_success:
  - .travis/patch.sh
  - .travis/deploy.sh
