language: ruby
cache: bundler
sudo: false

git:
  depth: 1

#install: bundle install

before_script:
  - .travis/export_env.sh TRAVIS_BUILD_ID TRAVIS_BUILD_NUMBER

script:
  - bundle exec jekyll build
  - .travis/patch.sh

after_success:
  - .travis/deploy.sh
