dist: bionic
language: ruby
rvm: 2.6.5
cache: bundler

git:
  depth: 1
  submodules: false

env:
  global:
    - JEKYLL_ENV=production
    - LC_ALL=C.UTF-8
  jobs:
    - JEKYLL_VERSION=4.0.1
    - JEKYLL_VERSION=4.1.0

script: bundle exec jekyll build --trace
