language: ruby
cache: bundler
sudo: false

git:
  depth: 1
  submodules: false

#install: bundle install

before_script:
  - .travis/prepare.sh

script:
  - bundle exec jekyll build

after_success:
  - .travis/patch.sh
  - .travis/deploy.sh
