language: ruby
cache: bundler
sudo: false

git:
  depth: 1

branches:
  only:
    - master

#install: bundle install

script:
  - bundle exec jekyll build
  - .travis/patch.sh

after_success:
  - .travis/deploy.sh
